TareaHelpers/TareaHelpers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TareaHelpers.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TareaHelpers/TareaHelpers/Controllers/RegistrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using TareaHelpers.Datos;



namespace TareaHelpers.Controllers
{
    public class RegistrosController : Controller
    {
        // GET: Registros
        public ActionResult Index()
        {
            return View();
        }


       
        public ActionResult Registro()
        {

            return View();

        }

        
        [HttpPost]
        public ActionResult Registro(Datos.Models.BindingModels.RegistroUsuariosBindingModel model, string correr, string bailar, string cantar, string pintar)
        {

            
            ViewBag.Nombre = model.Nombre;
            ViewBag.Apellido = model.Apellido;
            ViewBag.Cedula = model.Cedula;
            ViewBag.Sexo = model.Sexo;
            ViewBag.Ocupacion = model.Ocupacion;
            ViewBag.CheckBox = model.CheckBox;
            ViewBag.Correo = model.Correo;
            ViewBag.Edad = model.Edad;
            ViewBag.Telefono = model.Telefono;

            if (correr == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Correr";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }
            if (bailar == "true" && correr == "true")
            {
                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Bailar, Cantar";
            }
            else
            {
                model.CheckBox.CompareTo(false);
            }
            if(bailar == "true")
            {
                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Bailar";
            }
            else
            {
                model.CheckBox.CompareTo(false);
            }
            ////////////////////////////////////////////////////////////////



            if (cantar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Cantar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }


            if (pintar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }


            if (cantar == "true" && pintar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar, Cantar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }


            //////////////////////////////////////////////////////


            if (cantar == "true" && pintar == "true" && correr == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar Cantar Correr";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }

            if (cantar == "true" && pintar == "true" && bailar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar Cantar Bailar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }

            if (cantar == "true" && pintar == "true" && correr == "true" && bailar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar Cantar Correr bailar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }

            //////////////////////////////////////////////////////////////////////


            if (cantar == "true" && correr == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Cantar, Correr";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }

            if (cantar == "true" && bailar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Cantar, Bailar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }

            /////////////////////////////////////////////////////////////////////////////////

            if (pintar == "true" && correr == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar, Correr";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }

            if (pintar == "true" && bailar == "true")
            {

                model.CheckBox.CompareTo(true);
                ViewBag.CheckBox = "Pintar, Bailar";
            }
            else
            {
                model.CheckBox.CompareTo(false);


            }





            /*ViewBag.Nombre = gua.Nombre;*/


            if (ModelState.IsValid)
            {
                return View("Resultado");
            }


            return View(model);

        }

       /* public ActionResult Resultado(Datos.Models.BindingModels.RegistroUsuariosBindingModel ver)
        {
           
            

           

            return View("Resultado");
        }*/

    }

    internal class NombreCheckBox
    {
    }
}

TareaHelpers/TareaHelpers/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TareaHelpers/TareaHelpers/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TareaHelpers/TareaHelpers/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

TareaHelpers/TareaHelpers/Views/Registros/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Tarea de Programacion</h2>
@Html.ActionLink("Registrate","Registro","Registros",null, new { @class = "btn btn-primary"} )

TareaHelpers/TareaHelpers/Views/Registros/Registro.cshtml
@using TareaHelpers.Datos.Models.BindingModels


@model TareaHelpers.Datos.Models.BindingModels.RegistroUsuariosBindingModel

@{
    ViewBag.Title = "Registro";
}

<h2>Registro</h2>





<form action="/Registros/Registro" method="post">

    <div class="form-row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Cedula)

            @Html.TextBoxFor(m => m.Cedula, new { @class = "form-control" })



            @Html.ValidationMessageFor(m => m.Cedula, "", new { @class = "text-danger" })

        </div>
    </div>


    <div class="form-row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Nombre)
            @Html.EditorFor(m => m.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-row">

        <div class="col-md-12">

            @Html.LabelFor(m => m.Apellido)
            @Html.EditorFor(m => m.Apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Apellido, "", new { @class = "text-danger" })
        </div>

    </div>


    <div class="form-row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Edad)
            @Html.EditorFor(m => m.Edad, "", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Edad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Telefono)
            @Html.EditorFor(m => m.Telefono, "", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Telefono, "", new { @class = "text-damger" })
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Correo)
            @Html.EditorFor(m => m.Correo, "", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Correo, "", new { @class = "text-damger" })
        </div>
    </div>


    <div class="form-row">

        <div class="col-md-12">

            @Html.LabelFor(m => m.Ocupacion)

            <h6>Casado</h6>
            @Html.RadioButtonFor(m => m.Ocupacion, "Casado")

            <h6>Soltero</h6>
            @Html.RadioButtonFor(m => m.Ocupacion, "Soltero")

            <h6>Viudo</h6>
            @Html.RadioButtonFor(m => m.Ocupacion, "Viudo")

            <h6>Union Libre</h6>
            @Html.RadioButtonFor(m => m.Ocupacion, "Union Libre")
            @Html.ValidationMessageFor(m => m.Ocupacion, "", new { @class = "text-danger" })

        </div>

    </div>




    <div class="form-row">

        <div class="col-md-12">

            @Html.LabelFor(m => m.Sexo)
            @Html.DropDownListFor(m => m.Sexo,
                    new SelectList(Enum.GetValues(typeof(Gender))),
                    "Select Gender")

            @Html.ValidationMessageFor(m => m.Sexo, "", new { @class = "text-danger" })
        </div>

    </div>


    <div class="form-row">

        <div class="col-md-12">

            @Html.LabelFor(m => m.CheckBox)

            @Html.CheckBox("correr", false)
            Correr
            @Html.CheckBox("bailar", false)
            Bailar
            @Html.CheckBox("cantar", false)
            Cantar
            @Html.CheckBox("pintar", false)
            Pintar
            @Html.ValidationMessageFor(m => m.CheckBox, "", new { @class = "text-danger" })
        </div>

    </div>








    <div class="form-row">
        <div class="col-md-12">

            <input type="submit" value="Enviar" class="btn btn-primary" />

            @Html.ActionLink("Atras", "Registro", "Registros", null, new { @class = "btn btn-primary" })

        </div>
    </div>





</form>

TareaHelpers/TareaHelpers/Views/Registros/Resultado.cshtml
@model TareaHelpers.Datos.Models.BindingModels.RegistroUsuariosBindingModel


@{
    Layout = null;
    ViewBag.Title = "Resultado";


}





<!DOCTYPE html>

<html>

<head>

    <meta name="viewport" content="Width=device-width" />
    <title>Registro</title>
</head>
<body>

    <h1>
        Su Registro se hizo correctamente
    </h1>

    <div class="form-row">
        <div class="col-md-12">
            <table class="col-md-10">
                <tr>
                    <td>
                        <label>Nombre: @ViewBag.Nombre </label>
                        <br />
                        <label>Apellido: @ViewBag.Apellido </label>
                        <br />
                        <label>Cedula: @ViewBag.Cedula </label>
                        <br />
                        <label>Sexo: @ViewBag.Sexo </label>
                        <br />
                        <label>Ocupacion: @ViewBag.Ocupacion </label>
                        <br />
                        <label>Hobby: @ViewBag.CheckBox</label>
                        <br />
                        <label>Edad: @ViewBag.Edad</label>
                        <br />
                        <label>Correo: @ViewBag.Correo</label>
                        <br />
                        <label>Telefono: @ViewBag.Telefono</label>
                        <br />


                    </td>
                </tr>
            </table>
        </div>
    </div>


   
</body>


</html>

TareaHelpers/TareaHelpers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Registrate", "Registro", "Registros", null, new { @class = "btn btn-primary" })
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>




                </button>

            </div>
            <div class="navbar-collapse collapse">
               
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>